import type { Property } from "./types"

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Apartamento Moderno no Centro",
    description:
      "Lindo apartamento com 2 quartos, sala ampla, cozinha planejada e área de serviço. Localizado no coração de Pato Branco, próximo a comércios e serviços. O imóvel conta com acabamentos modernos, pisos em porcelanato e janelas amplas que proporcionam excelente iluminação natural. A localização privilegiada oferece fácil acesso ao transporte público e principais avenidas da cidade.",
    price: 1800,
    address: "Rua Tocantins, 123",
    neighborhood: "Centro",
    bedrooms: 2,
    bathrooms: 1,
    area: 65,
    images: ["/modern-apartment-living-room.png", "/modern-kitchen.png", "/bedroom-with-natural-light.jpg"],
    amenities: ["Ar condicionado", "Internet", "Portaria 24h"],
    type: "apartment",
    petFriendly: false,
    furnished: true,
    parking: true,
    createdAt: "2024-01-15",
    landlord: {
      id: "1",
      name: "Maria Silva",
      avatar: "/diverse-woman-avatar.png",
    },
  },
  {
    id: "2",
    title: "Casa Familiar no Bairro Brasília",
    description:
      "Casa espaçosa com 3 quartos, quintal amplo, garagem para 2 carros. Ideal para famílias que buscam tranquilidade e espaço. A propriedade possui área gourmet completa com churrasqueira, jardim bem cuidado e lavanderia independente. Localizada em rua residencial tranquila, próxima a escolas e parques.",
    price: 2500,
    address: "Rua das Flores, 456",
    neighborhood: "Brasília",
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    images: ["/modern-family-house.png", "/spacious-living-room.png", "/placeholder-91io5.png"],
    amenities: ["Quintal", "Churrasqueira", "Lavanderia"],
    type: "house",
    petFriendly: true,
    furnished: false,
    parking: true,
    createdAt: "2024-01-10",
    landlord: {
      id: "2",
      name: "João Santos",
      avatar: "/man-avatar.png",
    },
  },
  {
    id: "3",
    title: "Studio Compacto e Moderno",
    description:
      "Studio perfeito para estudantes ou profissionais solteiros. Ambiente integrado, mobiliado e com localização privilegiada. O espaço foi otimizado para oferecer máximo conforto em área compacta, com móveis planejados e decoração moderna. Inclui cozinha americana equipada e banheiro completo.",
    price: 1200,
    address: "Av. Tupi, 789",
    neighborhood: "Centro",
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    images: ["/modern-studio-apartment.png", "/compact-kitchen.png", "/studio-bedroom-area.jpg"],
    amenities: ["Wi-Fi", "Mobiliado", "Academia"],
    type: "studio",
    petFriendly: false,
    furnished: true,
    parking: false,
    createdAt: "2024-01-12",
    landlord: {
      id: "3",
      name: "Ana Costa",
      avatar: "/diverse-woman-avatar.png",
    },
  },
  {
    id: "4",
    title: "Apartamento com Vista Panorâmica",
    description:
      "Apartamento no último andar com vista incrível da cidade. 3 quartos, suíte, varanda gourmet e acabamento de primeira. O imóvel oferece uma experiência única com amplas janelas, varanda com vista panorâmica e acabamentos de luxo. Localizado em edifício moderno com infraestrutura completa.",
    price: 3200,
    address: "Rua Amazonas, 321",
    neighborhood: "Jardim Primavera",
    bedrooms: 3,
    bathrooms: 2,
    area: 95,
    images: ["/apartment-with-city-view.jpg", "/luxury-bedroom-suite.jpg", "/gourmet-balcony.jpg"],
    amenities: ["Varanda", "Suíte", "Elevador", "Piscina"],
    type: "apartment",
    petFriendly: true,
    furnished: false,
    parking: true,
    createdAt: "2024-01-08",
    landlord: {
      id: "4",
      name: "Carlos Oliveira",
      avatar: "/man-avatar.png",
    },
  },
  {
    id: "5",
    title: "Casa Aconchegante no Bairro Pinheiros",
    description:
      "Casa térrea com 2 quartos, sala de estar, cozinha americana e área gourmet. Perfeita para casais ou pequenas famílias. A propriedade conta com jardim frontal, área gourmet nos fundos e garagem coberta. Ambiente acolhedor em bairro residencial tranquilo.",
    price: 2000,
    address: "Rua dos Pinheiros, 654",
    neighborhood: "Pinheiros",
    bedrooms: 2,
    bathrooms: 1,
    area: 80,
    images: ["/cozy-house-exterior.jpg", "/american-kitchen.jpg", "/gourmet-area.jpg"],
    amenities: ["Área Gourmet", "Jardim", "Garagem"],
    type: "house",
    petFriendly: true,
    furnished: false,
    parking: true,
    createdAt: "2024-01-05",
    landlord: {
      id: "5",
      name: "Fernanda Lima",
      avatar: "/diverse-woman-avatar.png",
    },
  },
  {
    id: "6",
    title: "Apartamento Econômico no Bairro Industrial",
    description:
      "Apartamento simples e funcional, ideal para quem busca economia sem abrir mão do conforto. Próximo ao distrito industrial. O imóvel oferece boa relação custo-benefício, com ambientes bem distribuídos e localização estratégica para quem trabalha na região industrial.",
    price: 1400,
    address: "Rua Industrial, 987",
    neighborhood: "Industrial",
    bedrooms: 2,
    bathrooms: 1,
    area: 55,
    images: ["/simple-apartment-living-room.jpg", "/functional-kitchen.jpg", "/simple-bedroom.jpg"],
    amenities: ["Portaria", "Playground"],
    type: "apartment",
    petFriendly: false,
    furnished: false,
    parking: true,
    createdAt: "2024-01-03",
    landlord: {
      id: "6",
      name: "Roberto Mendes",
      avatar: "/man-avatar.png",
    },
  },
]
