import type { Conversation, ChatMessage } from "./types"
import { mockUser } from "./mock-user-data"
import { mockProperties } from "./mock-data"

const otherUsers = [
  {
    id: "landlord-1",
    name: "Maria Silva",
    email: "maria@email.com",
    phone: "(46) 98888-8888",
    avatar: "/diverse-woman-avatar.png",
    createdAt: "2023-12-01",
    role: "landlord" as const,
  },
  {
    id: "landlord-2",
    name: "João Santos",
    email: "joao.santos@email.com",
    phone: "(46) 96666-6666",
    avatar: "/man-avatar.png",
    createdAt: "2023-10-20",
    role: "landlord" as const,
  },
  {
    id: "tenant-1",
    name: "Ana Costa",
    email: "ana@email.com",
    phone: "(46) 97777-7777",
    avatar: "/diverse-woman-avatar.png",
    createdAt: "2023-11-15",
    role: "tenant" as const,
  },
]

export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    participants: [mockUser, otherUsers[0]],
    propertyId: "1",
    property: mockProperties[0],
    proposalId: "prop-1",
    lastMessage: {
      id: "msg-5",
      conversationId: "conv-1",
      senderId: "landlord-1",
      sender: otherUsers[0],
      content:
        "Perfeito! Podemos agendar para amanhã às 14h. O endereço é Rua Tocantins, 123. Qualquer dúvida me chame!",
      type: "text",
      createdAt: "2024-01-17T10:30:00Z",
    },
    unreadCount: 1,
    createdAt: "2024-01-16T09:00:00Z",
    updatedAt: "2024-01-17T10:30:00Z",
  },
  {
    id: "conv-2",
    participants: [mockUser, otherUsers[1]],
    propertyId: "2",
    property: mockProperties[1],
    lastMessage: {
      id: "msg-8",
      conversationId: "conv-2",
      senderId: "user-1",
      sender: mockUser,
      content: "Entendo. Obrigado pela resposta. Vou continuar procurando.",
      type: "text",
      createdAt: "2024-01-15T16:45:00Z",
    },
    unreadCount: 0,
    createdAt: "2024-01-13T14:20:00Z",
    updatedAt: "2024-01-15T16:45:00Z",
  },
  {
    id: "conv-3",
    participants: [mockUser, otherUsers[2]],
    propertyId: "3",
    property: mockProperties[2],
    lastMessage: {
      id: "msg-12",
      conversationId: "conv-3",
      senderId: "tenant-1",
      sender: otherUsers[2],
      content: "Ótimo! Muito obrigada. Vou providenciar a documentação.",
      type: "text",
      createdAt: "2024-01-16T11:20:00Z",
    },
    unreadCount: 0,
    createdAt: "2024-01-14T08:30:00Z",
    updatedAt: "2024-01-16T11:20:00Z",
  },
]

export const mockMessages: Record<string, ChatMessage[]> = {
  "conv-1": [
    {
      id: "msg-1",
      conversationId: "conv-1",
      senderId: "user-1",
      sender: mockUser,
      content:
        "Olá! Tenho muito interesse no apartamento. Gostaria de agendar uma visita para esta semana se possível.",
      type: "text",
      createdAt: "2024-01-16T09:00:00Z",
      readAt: "2024-01-16T09:05:00Z",
    },
    {
      id: "msg-2",
      conversationId: "conv-1",
      senderId: "landlord-1",
      sender: otherUsers[0],
      content: "Olá João! Que bom saber do seu interesse. Posso agendar sim. Que dias funcionam melhor para você?",
      type: "text",
      createdAt: "2024-01-16T09:15:00Z",
      readAt: "2024-01-16T09:20:00Z",
    },
    {
      id: "msg-3",
      conversationId: "conv-1",
      senderId: "user-1",
      sender: mockUser,
      content: "Terça ou quarta-feira à tarde seria ideal. Tenho flexibilidade de horário.",
      type: "text",
      createdAt: "2024-01-16T09:25:00Z",
      readAt: "2024-01-16T09:30:00Z",
    },
    {
      id: "msg-4",
      conversationId: "conv-1",
      senderId: "user-1",
      sender: mockUser,
      content: "Ah, e gostaria de saber se aceita pets. Tenho um gato pequeno.",
      type: "text",
      createdAt: "2024-01-16T09:26:00Z",
      readAt: "2024-01-16T09:35:00Z",
    },
    {
      id: "msg-5",
      conversationId: "conv-1",
      senderId: "landlord-1",
      sender: otherUsers[0],
      content:
        "Perfeito! Podemos agendar para amanhã às 14h. O endereço é Rua Tocantins, 123. Qualquer dúvida me chame!",
      type: "text",
      createdAt: "2024-01-17T10:30:00Z",
    },
  ],
  "conv-2": [
    {
      id: "msg-6",
      conversationId: "conv-2",
      senderId: "user-1",
      sender: mockUser,
      content:
        "Boa tarde! Enviei uma proposta para a casa no Bairro Brasília. Gostaria de saber se há possibilidade de negociação no valor.",
      type: "text",
      createdAt: "2024-01-13T14:20:00Z",
      readAt: "2024-01-13T15:00:00Z",
    },
    {
      id: "msg-7",
      conversationId: "conv-2",
      senderId: "landlord-2",
      sender: otherUsers[1],
      content:
        "Olá João! Obrigado pelo interesse. Infelizmente o valor não tem margem para negociação no momento. O preço já está bem competitivo para a região.",
      type: "text",
      createdAt: "2024-01-15T16:30:00Z",
      readAt: "2024-01-15T16:40:00Z",
    },
    {
      id: "msg-8",
      conversationId: "conv-2",
      senderId: "user-1",
      sender: mockUser,
      content: "Entendo. Obrigado pela resposta. Vou continuar procurando.",
      type: "text",
      createdAt: "2024-01-15T16:45:00Z",
      readAt: "2024-01-15T17:00:00Z",
    },
  ],
  "conv-3": [
    {
      id: "msg-9",
      conversationId: "conv-3",
      senderId: "tenant-1",
      sender: otherUsers[2],
      content:
        "Olá! Vi que você aprovou minha proposta para o studio. Muito obrigada! Quando podemos finalizar o contrato?",
      type: "text",
      createdAt: "2024-01-14T08:30:00Z",
      readAt: "2024-01-14T09:00:00Z",
    },
    {
      id: "msg-10",
      conversationId: "conv-3",
      senderId: "user-1",
      sender: mockUser,
      content:
        "Oi Ana! Que bom que deu certo. Podemos nos encontrar esta semana para assinar o contrato. Você já tem toda a documentação?",
      type: "text",
      createdAt: "2024-01-14T09:15:00Z",
      readAt: "2024-01-14T10:00:00Z",
    },
    {
      id: "msg-11",
      conversationId: "conv-3",
      senderId: "tenant-1",
      sender: otherUsers[2],
      content: "Tenho quase tudo. Só preciso atualizar o comprovante de renda. Posso levar na sexta-feira?",
      type: "text",
      createdAt: "2024-01-16T10:45:00Z",
      readAt: "2024-01-16T11:00:00Z",
    },
    {
      id: "msg-12",
      conversationId: "conv-3",
      senderId: "tenant-1",
      sender: otherUsers[2],
      content: "Ótimo! Muito obrigada. Vou providenciar a documentação.",
      type: "text",
      createdAt: "2024-01-16T11:20:00Z",
    },
  ],
}
